spring.application.name=tp1_ssd_e_back_service
spring.datasource.url=jdbc:h2:mem:account-db
spring.h2.console.enabled=true
#spring.datasource.username=sa
#spring.datasource.password=
server.port=8080

